name: Integration Tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  linux-tests-postgres:
    name: Run tests on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add commits/tags to build against other DuckDB versions
        duckdb_version: [ '<submodule_version>' ]
        arch: ['linux_amd64']
        vcpkg_version: [ '2023.04.15' ]
        include:
          - arch: 'linux_amd64'
            vcpkg_triplet: 'x64-linux'

    env:
      VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_triplet }}
      GEN: Ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    steps:
    - name: Free disk space 1
      uses: endersonmenezes/free-disk-space@v2.1.1
      continue-on-error: true
      with:
#          remove_android: true # ~9.5GB in #52s
#          remove_dotnet: true
        remove_haskell: true # ~6.5GB in ~3s
        remove_tool_cache: true # ~4.8GB in ~17s
#          remove_swap: true
#          remove_packages_one_command: true # ~7.5 GB in ~94s
        testing: false

    - name: Install required ubuntu packages
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq build-essential cmake ninja-build ccache python3

    - name: Setup PostgreSQL for Linux/macOS/Windows
      uses: ikalnytskyi/action-setup-postgres@v7
      with:
        postgres-version: '15'
        username: 'postgres'
        password: 'postgres'
        database: 'postgres'
        port: '5432'
        ssl: true

    - name: Test Postgres Setup
      run: |
        psql -c "SELECT 42"
      env:
        PGSERVICE: postgres

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Checkout DuckDB to version
      if: ${{ matrix.duckdb_version != '<submodule_version>'}}
      run: |
        cd duckdb
        git checkout ${{ matrix.duckdb_version }}

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb-postgres' }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 84bab45d415d22042bd0b9081aea57f362da3f35

    - name: Build extension
      env:
        GEN: ninja
        STATIC_LIBCPP: 1
      run: |
        make reldebug

    - name: Test extension
      env:
        POSTGRES_TEST_DATABASE_AVAILABLE: 1
        LOCAL_EXTENSION_REPO: 'build/reldebug/repository'
        PGSERVICE: postgres
      run: |
        psql -c "SELECT 43"
        source ./create-postgres-tables.sh
        ./build/reldebug/test/unittest --autoloading available
